name: Install from Mirror Example
on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SOURCE: mirror

jobs:
  latest-version:
    name: Latest version
    strategy:
      fail-fast: false
      matrix:
        os: [ "windows-latest", "ubuntu-24.04" ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - uses: ./
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          # crc: "latest"                    # Fails on macos for version above 1.27.0
          helm: "latest"
          kam: "latest"
          kamel: "latest"
          kn: "latest"
          oc: "latest"
          # operator-sdk: "latest"           # Not available on windows
          opm: "latest"
          # openshift-install: "latest"      # Not available on windows
          tkn: "latest"

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        shell: bash
        run: |
          set -x
          helm version
          kam version
          kamel version
          kn version
          oc version
          opm version
          tkn version || true

  known-version:
    name: Known version
    strategy:
      fail-fast: false
      matrix:
        os: [ "windows-latest", "ubuntu-24.04" ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - uses: ./
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          helm: "3.5"
          kam: "1"
          kamel: "1"
          kn: "0.15"
          oc: "4"
          # operator-sdk: "4.7"         # Not available on windows
          opm: "4.6"
          # openshift-install: "4.x"    # Not available on windows
          tkn: "0.17"

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        shell: bash
        run: |
          set -x
          helm version
          kam version
          kamel version
          kn version
          oc version
          opm version
          tkn version || true

  latest-version-linux-macos:
    name: Latest openshift-install on linux & macOS
    strategy:
      fail-fast: false
      matrix:
        os: [ "macos-latest", "ubuntu-24.04" ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - uses: ./
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          openshift-install: "latest"

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        run: |
          set -x
          openshift-install version

  latest-version-operator-sdk:
    name: Latest operator-sdk on linux
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - uses: ./
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          operator-sdk: "latest"

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        run: |
          set -x
          operator-sdk version

  known-version-linux-macos:
    name: Known openshift-install on linux & macOS
    strategy:
      fail-fast: false
      matrix:
        os: [ "macos-latest", "ubuntu-24.04" ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - uses: ./
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          openshift-install: "4.x"

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        run: |
          set -x
          openshift-install version

  known-version-operator-sdk:
    name: Known operator-sdk on linux
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - uses: ./
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          operator-sdk: "4.7"

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        run: |
          set -x
          operator-sdk version

  known-version-linux:
    name: Known version only linux
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - uses: ./
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          butane: "latest"
          oc: "4"
          opm: "4"             # Only available on linux

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        run: |
          set -x
          butane --version
          oc version
          opm version

  latest-version-linux-arm64:
    name: Latest OCP tools on linux arm64
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v7

      - uses: ./
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          oc: "latest"
          openshift-install: "latest"

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        run: |
          set -x
          oc version
          openshift-install version

  latest-version-linux-windows:
    name: Install CRC
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - uses: ./
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          crc: "latest"

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        shell: bash
        run: |
          set -x
          crc version
